### ISSUE TITLE
More details on how to setup the project and NGROK

### ISSUE THREAD

**Issue by MacedoRAC** [techenby/pokeprint#5]
I came across this repo and seems interesting. I downloaded it and set it up locally, but I'm not exactly sure how to configure NGROK to work with this project.

Could you please provide more details on how to do it?

I'm a laravel developer and a 3D printing enthusiast so I'll maybe do some PRs

Thanks in advance.

**Comment by techenby** [comment]
Hi! Sorry I just saw this today, I'll add some more information to the Readme :)
